// store of http requests for testing the Express app. These are used in the VS Code REST Client extension, 
// which allows me to send http requests and view the responses without leaving VS Code. Each request is separated 
// by a line of three hashes . I can click on the "Send Request" link above each request to execute it.

@baseUrl = http://localhost:5000
@username1 = testuser1
@password1 = testpass123

@username2 = testuser2
@password2 = testpass456

@username3 = alice
@password3 = secret123

###
# Get all books. 
GET {{baseUrl}}/

###
# Attempt registration of user1
POST {{baseUrl}}/register
Content-Type: application/json

{
    "username": "{{username1}}",
    "password": "{{password1}}"
}

###
# Attempt registration of user2
POST {{baseUrl}}/register       
Content-Type: application/json

{
    "username": "{{username2}}",
    "password": "{{password2}}"
}

###
# Attempt registration of user3
POST {{baseUrl}}/register       
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{password3}}"
}

###
#Return users list
GET {{baseUrl}}/allusers    


###
# Attempt login of user 3
POST {{baseUrl}}/customer/login 
Content-Type: application/json

{
    "username": "{{username3}}",
    "password": "{{password3}}"
}

###
# Add a review for book of ISBN. Try this with different user logins. It should modify an existing review.  
# Note the username is identified from the session following login, so we don't include it in the request.
PUT {{baseUrl}}/customer/auth/review/1
Content-Type: application/json

{
    "review": "Not bad, but could have done with more big words."
}

###
# Add a review for book of ISBN.Same as before but with different review content. 
PUT {{baseUrl}}/customer/auth/review/1
Content-Type: application/json

{
    "review": "Pretty good. Though I could do better myself."
}


###
# Delete a review
# Note the username is identified from the session.
DELETE {{baseUrl}}/customer/auth/review/1
